#define PHOTON_GRID_SIZE 256
#define PHOTON_RADIUS (1.0/PHOTON_GRID_SIZE)
#define PHOTON_CELL_SIZE (1.0/(PHOTON_GRID_SIZE))

#define PHOTONS_LOD	11

#define PHOTON_DIMENSION (1 << PHOTONS_LOD)
#define SHADOWMAP_DIMENSION (PHOTON_DIMENSION > 2048 ? PHOTON_DIMENSION : 2048)
#define PHOTON_TRACE_MAX_BOUNCES 2
#define RAY_TRACING_MAX_BOUNCES 2
#define PATH_TRACING_MAX_BOUNCES 5
#define LIGHT_SOURCE_RADIUS 0.01
#define HASH_CAPACITY (PHOTON_GRID_SIZE * PHOTON_GRID_SIZE + 1)
#define DESIRED_PHOTONS (37)

#define CS_1D_GROUPSIZE 1024
#define CS_2D_GROUPSIZE 32

#define PHOTON_WAVES 16

#define BOXED_PHOTONS_LOD 1
#define BOXED_PHOTONS ((1 << BOXED_PHOTONS_LOD)*(1 << BOXED_PHOTONS_LOD))

//#define COMPACT_PAYLOAD

//#define DEBUG_PHOTONS
#define DEBUG_STRATEGY 1

#define ADAPTIVE_POWER 0.5
#define ADAPTIVE_STRATEGY 1

#define USE_VOLUME_GRID true

#ifndef DEBUG_PHOTONS
#define SHOW_DIRECT
#endif

#define SHOW_INDIRECT

#define MAJORANT_VOLUMEN_CELL_DIM 16

//#define REBUILT_ADS_EVERY_FRAME